#!/usr/bin/perl
use strict;
my %procs;
my $logdir = "/tmp/runon/$$";
my @pids;
my $cmd = pop(@ARGV);
mkdir "/tmp/runon" unless -d "/tmp/runon";
mkdir $logdir unless -d $logdir;
while (my $srv = shift(@ARGV)){
	if (-f $srv){
		open (my $infile,'<',$srv);
		while ( my $srv = <$infile>){
			chomp($srv);
			&process($srv);
		}
	} else {
		&process($srv);
	}
}
print "Creating logs in $logdir\n";
waitpid($_,0) for @pids; 
print "DONE\n";

sub process{
	my $ret;
	my ($srv) = @_;
	print "Running \"$cmd\" on $srv\n";
	my $log = $logdir . '/' . $srv . '.txt';
	my $pid = fork() or exec('ssh root@' . $srv . ' "' . $cmd. '" > ' . $log . ' 2> ' . $log . '.err' );
	push @pids,$pid;
	$procs{$pid} = $srv;
}
